/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClockResp,
  LegacyCalendarDay,
  LegacyClock,
  Market,
  PublicCalendarResp,
} from '../models/index';
import {
    ClockRespFromJSON,
    ClockRespToJSON,
    LegacyCalendarDayFromJSON,
    LegacyCalendarDayToJSON,
    LegacyClockFromJSON,
    LegacyClockToJSON,
    MarketFromJSON,
    MarketToJSON,
    PublicCalendarRespFromJSON,
    PublicCalendarRespToJSON,
} from '../models/index';

export interface CalendarRequest {
    market: Market;
    start?: Date;
    end?: Date;
    timezone?: CalendarTimezoneEnum;
}

export interface ClockRequest {
    markets?: string;
    time?: Date;
}

export interface LegacyCalendarRequest {
    start?: Date;
    end?: Date;
    dateType?: LegacyCalendarDateTypeEnum;
}

/**
 * 
 */
export class CalendarApi extends runtime.BaseAPI {

    /**
     * This endpoint returns the market calendar.
     * Get Market Calendar
     */
    async calendarRaw(requestParameters: CalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicCalendarResp>> {
        if (requestParameters['market'] == null) {
            throw new runtime.RequiredError(
                'market',
                'Required parameter "market" was null or undefined when calling calendar().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['timezone'] != null) {
            queryParameters['timezone'] = requestParameters['timezone'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v3/calendar/{market}`;
        urlPath = urlPath.replace(`{${"market"}}`, encodeURIComponent(String(requestParameters['market'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicCalendarRespFromJSON(jsonValue));
    }

    /**
     * This endpoint returns the market calendar.
     * Get Market Calendar
     */
    async calendar(requestParameters: CalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicCalendarResp> {
        const response = await this.calendarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This API serves information about multiple markets: the current time, if it\'s a market day, the current phase of the market, etc. 
     * Get Market Clock
     */
    async clockRaw(requestParameters: ClockRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClockResp>> {
        const queryParameters: any = {};

        if (requestParameters['markets'] != null) {
            queryParameters['markets'] = requestParameters['markets'];
        }

        if (requestParameters['time'] != null) {
            queryParameters['time'] = (requestParameters['time'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v3/clock`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClockRespFromJSON(jsonValue));
    }

    /**
     * This API serves information about multiple markets: the current time, if it\'s a market day, the current phase of the market, etc. 
     * Get Market Clock
     */
    async clock(requestParameters: ClockRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClockResp> {
        const response = await this.clockRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The calendar API serves the full list of market days from 1970 to 2029. It can also be queried by specifying a start and/or end time to narrow down the results. In addition to the dates, the response also contains the specific open and close times for the market days, taking into account early closures. 
     * Get US Market Calendar
     */
    async legacyCalendarRaw(requestParameters: LegacyCalendarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LegacyCalendarDay>>> {
        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = (requestParameters['start'] as any).toISOString();
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = (requestParameters['end'] as any).toISOString();
        }

        if (requestParameters['dateType'] != null) {
            queryParameters['date_type'] = requestParameters['dateType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/calendar`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LegacyCalendarDayFromJSON));
    }

    /**
     * The calendar API serves the full list of market days from 1970 to 2029. It can also be queried by specifying a start and/or end time to narrow down the results. In addition to the dates, the response also contains the specific open and close times for the market days, taking into account early closures. 
     * Get US Market Calendar
     */
    async legacyCalendar(requestParameters: LegacyCalendarRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LegacyCalendarDay>> {
        const response = await this.legacyCalendarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The clock API serves the current market timestamp, whether or not the market is currently open, as well as the times of the next market open and close. 
     * Get US Market Clock
     */
    async legacyClockRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LegacyClock>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-KEY-ID"] = await this.configuration.apiKey("APCA-API-KEY-ID"); // API_Key authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["APCA-API-SECRET-KEY"] = await this.configuration.apiKey("APCA-API-SECRET-KEY"); // API_Secret authentication
        }


        let urlPath = `/v2/clock`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LegacyClockFromJSON(jsonValue));
    }

    /**
     * The clock API serves the current market timestamp, whether or not the market is currently open, as well as the times of the next market open and close. 
     * Get US Market Clock
     */
    async legacyClock(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LegacyClock> {
        const response = await this.legacyClockRaw(initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const CalendarTimezoneEnum = {
    Utc: 'UTC'
} as const;
export type CalendarTimezoneEnum = typeof CalendarTimezoneEnum[keyof typeof CalendarTimezoneEnum];
/**
 * @export
 */
export const LegacyCalendarDateTypeEnum = {
    Trading: 'TRADING',
    Settlement: 'SETTLEMENT'
} as const;
export type LegacyCalendarDateTypeEnum = typeof LegacyCalendarDateTypeEnum[keyof typeof LegacyCalendarDateTypeEnum];
