/* tslint:disable */
/* eslint-disable */
/**
 * Trading API
 * Alpaca\'s Trading API is a modern platform for algorithmic trading.
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: support@alpaca.markets
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Trading API hosts. Paper is the safe default; live trades real money.
 *
 * Prefer the `paper` flag on `Configuration` (or the top-level `Alpaca` client)
 * over hand-setting `basePath` so "accidentally on the wrong environment" is
 * harder to do.
 */
import { buildApiError, FetchError } from "../errors";
import { RateLimiter } from "../rate-limit";
import type { RateLimitConfig } from "../rate-limit";

export { RateLimiter } from "../rate-limit";
export type { RateLimitConfig } from "../rate-limit";

// Re-exported from the shared error module so `trading.ApiError` (etc.) resolve
// to the SAME class identity as `marketData.*` and the top-level `errors.*`.
export {
    ResponseError,
    ApiError,
    AuthError,
    PermissionError,
    NotFoundError,
    ValidationError,
    RateLimitError,
    FetchError,
} from "../errors";
export type { RateLimitInfo } from "../errors";

export const TRADING_PAPER_HOST = "https://paper-api.alpaca.markets";
export const TRADING_LIVE_HOST = "https://api.alpaca.markets";

export const BASE_PATH = TRADING_PAPER_HOST.replace(/\/+$/, "");

/**
 * Default User-Agent sent on every request so Alpaca can attribute SDK traffic.
 * Override via `Configuration.userAgent` (set to "" to disable).
 */
export const USER_AGENT = "@alpaca/sdk/0.0.0";

/**
 * Opt-in automatic retry policy. Disabled unless `maxRetries > 0`.
 */
export interface RetryConfig {
    maxRetries?: number; // max retry attempts after the initial request (default 0 = off)
    retryDelayMs?: number; // base backoff in ms for exponential backoff (default 500)
    maxDelayMs?: number; // cap for any single backoff delay in ms (default 30000)
    retryableStatuses?: number[]; // HTTP statuses eligible for retry (default 429,500,502,503,504)
    respectRetryAfter?: boolean; // honor a Retry-After response header (default true)
}

export interface ConfigurationParameters {
    basePath?: string; // override base path
    fetchApi?: FetchAPI; // override for fetch implementation
    middleware?: Middleware[]; // middleware to apply before/after fetch requests
    queryParamsStringify?: (params: HTTPQuery) => string; // stringify function for query strings
    username?: string; // parameter for basic security
    password?: string; // parameter for basic security
    apiKey?: string | Promise<string> | ((name: string) => string | Promise<string>); // parameter for apiKey security
    keyId?: string; // Alpaca API key id, sent as the APCA-API-KEY-ID header (use with `secret`)
    secret?: string; // Alpaca API secret, sent as the APCA-API-SECRET-KEY header (use with `keyId`)
    paper?: boolean; // select the paper (true, default) vs live (false) trading host; ignored if basePath is set explicitly
    accessToken?: string | Promise<string> | ((name?: string, scopes?: string[]) => string | Promise<string>); // parameter for oauth2 security
    headers?: HTTPHeaders; //header params we want to use on every request
    credentials?: RequestCredentials; //value for the credentials param we want to use on each request
    timeoutMs?: number; // per-request timeout in ms; aborts the fetch via AbortController when exceeded
    retry?: RetryConfig; // opt-in automatic retry/backoff policy
    rateLimit?: RateLimitConfig; // opt-in proactive client-side rate limiting (off unless set)
    userAgent?: string; // override the default User-Agent header (set to "" to disable)
}

export class Configuration {
    private _rateLimiter?: RateLimiter | null;

    constructor(private configuration: ConfigurationParameters = {}) {}

    set config(configuration: Configuration) {
        this.configuration = configuration;
        this._rateLimiter = undefined;
    }

    get basePath(): string {
        // An explicit basePath always wins. Otherwise derive the host from the
        // `paper` flag, defaulting to the (safe) paper environment.
        if (this.configuration.basePath != null) {
            return this.configuration.basePath;
        }
        return this.configuration.paper === false ? TRADING_LIVE_HOST : TRADING_PAPER_HOST;
    }

    get fetchApi(): FetchAPI | undefined {
        return this.configuration.fetchApi;
    }

    get middleware(): Middleware[] {
        return this.configuration.middleware || [];
    }

    get queryParamsStringify(): (params: HTTPQuery) => string {
        return this.configuration.queryParamsStringify || querystring;
    }

    get username(): string | undefined {
        return this.configuration.username;
    }

    get password(): string | undefined {
        return this.configuration.password;
    }

    get apiKey(): ((name: string) => string | Promise<string>) | undefined {
        const { apiKey, keyId, secret } = this.configuration;
        // Preferred ergonomic path: a keyId/secret pair maps cleanly onto
        // Alpaca's two distinct auth headers.
        if (keyId != null || secret != null) {
            if (!keyId || !secret) {
                throw new Error(
                    "Alpaca authentication requires both `keyId` and `secret`.",
                );
            }
            return (name: string) => {
                if (name === "APCA-API-KEY-ID") return keyId;
                if (name === "APCA-API-SECRET-KEY") return secret;
                throw new Error(`Unexpected API key header requested: "${name}".`);
            };
        }
        if (apiKey) {
            if (typeof apiKey === 'function') {
                return apiKey;
            }
            // A bare string would be sent for BOTH the key id and the secret
            // header, which Alpaca rejects. Fail loudly with guidance instead
            // of producing an opaque 403 at request time.
            throw new Error(
                "Passing `apiKey` as a string sends the same value for both " +
                "`APCA-API-KEY-ID` and `APCA-API-SECRET-KEY`. " +
                "Use `new Configuration({ keyId, secret })` instead.",
            );
        }
        return undefined;
    }

    get accessToken(): ((name?: string, scopes?: string[]) => string | Promise<string>) | undefined {
        const accessToken = this.configuration.accessToken;
        if (accessToken) {
            return typeof accessToken === 'function' ? accessToken : async () => accessToken;
        }
        return undefined;
    }

    get headers(): HTTPHeaders | undefined {
        return this.configuration.headers;
    }

    get credentials(): RequestCredentials | undefined {
        return this.configuration.credentials;
    }

    get timeoutMs(): number | undefined {
        return this.configuration.timeoutMs;
    }

    get retry(): RetryConfig | undefined {
        return this.configuration.retry;
    }

    get rateLimit(): RateLimitConfig | undefined {
        return this.configuration.rateLimit;
    }

    /**
     * Lazily-built, memoized rate limiter shared by every `Api` using this
     * `Configuration`. `undefined` when no `rateLimit` policy is configured.
     */
    get rateLimiter(): RateLimiter | undefined {
        if (this._rateLimiter === undefined) {
            this._rateLimiter = this.configuration.rateLimit
                ? new RateLimiter(this.configuration.rateLimit)
                : null;
        }
        return this._rateLimiter ?? undefined;
    }

    get userAgent(): string | undefined {
        return this.configuration.userAgent !== undefined ? this.configuration.userAgent : USER_AGENT;
    }
}

export const DefaultConfig = new Configuration();

/**
 * This is the base class for all generated API classes.
 */
export class BaseAPI {

    private static readonly jsonRegex = new RegExp('^(:?application\/json|[^;/ \t]+\/[^;/ \t]+[+]json)[ \t]*(:?;.*)?$', 'i');
    private middleware: Middleware[];

    constructor(protected configuration = DefaultConfig) {
        this.middleware = configuration.middleware;
    }

    withMiddleware<T extends BaseAPI>(this: T, ...middlewares: Middleware[]) {
        const next = this.clone<T>();
        next.middleware = next.middleware.concat(...middlewares);
        return next;
    }

    withPreMiddleware<T extends BaseAPI>(this: T, ...preMiddlewares: Array<Middleware['pre']>) {
        const middlewares = preMiddlewares.map((pre) => ({ pre }));
        return this.withMiddleware<T>(...middlewares);
    }

    withPostMiddleware<T extends BaseAPI>(this: T, ...postMiddlewares: Array<Middleware['post']>) {
        const middlewares = postMiddlewares.map((post) => ({ post }));
        return this.withMiddleware<T>(...middlewares);
    }

    /**
     * Check if the given MIME is a JSON MIME.
     * JSON MIME examples:
     *   application/json
     *   application/json; charset=UTF8
     *   APPLICATION/JSON
     *   application/vnd.company+json
     * @param mime - MIME (Multipurpose Internet Mail Extensions)
     * @return True if the given MIME is JSON, false otherwise.
     */
    protected isJsonMime(mime: string | null | undefined): boolean {
        if (!mime) {
            return false;
        }
        return BaseAPI.jsonRegex.test(mime);
    }

    protected async request(context: RequestOpts, initOverrides?: RequestInit | InitOverrideFunction): Promise<Response> {
        const { url, init } = await this.createFetchParams(context, initOverrides);
        const retry = this.configuration.retry;
        const maxRetries = retry?.maxRetries ?? 0;
        const method = (init.method || context.method || 'GET').toUpperCase();
        const idempotent = method === 'GET' || method === 'HEAD' || method === 'PUT' || method === 'DELETE' || method === 'OPTIONS';

        let attempt = 0;
        while (true) {
            const timeout = applyTimeout(this.configuration.timeoutMs, init.signal);
            let response: Response | undefined;
            let networkError: unknown;
            let release: (() => void) | undefined;
            try {
                // Proactively wait for a rate-limit slot (and honor any timeout/
                // caller abort while queued) before touching the network.
                release = await this.configuration.rateLimiter?.acquire(timeout.signal);
                response = await this.fetchApi(url, timeout.signal ? { ...init, signal: timeout.signal } : init);
            } catch (e) {
                // A transient network failure (DNS, connection reset, TLS) throws
                // a FetchError with no Response. Capture it so the retry policy
                // below can re-attempt it like a retryable status.
                networkError = e;
            } finally {
                timeout.cancel();
                release?.();
            }
            if (networkError !== undefined) {
                const canRetry = attempt < maxRetries
                    && idempotent
                    && isRetryableNetworkError(networkError);
                if (canRetry) {
                    await sleep(backoffDelay(attempt, retry));
                    attempt++;
                    continue;
                }
                throw networkError;
            }
            if (response && (response.status >= 200 && response.status < 300)) {
                return response;
            }
            const canRetry = attempt < maxRetries
                && isRetryableStatus(response!.status, retry)
                && (idempotent || response!.status === 429);
            if (canRetry) {
                await sleep(computeRetryDelay(response!, attempt, retry));
                attempt++;
                continue;
            }
            throw await buildApiError(response!);
        }
    }

    private async createFetchParams(context: RequestOpts, initOverrides?: RequestInit | InitOverrideFunction) {
        let url = this.configuration.basePath + context.path;
        if (context.query !== undefined && Object.keys(context.query).length !== 0) {
            // only add the querystring to the URL if there are query parameters.
            // this is done to avoid urls ending with a "?" character which buggy webservers
            // do not handle correctly sometimes.
            url += '?' + this.configuration.queryParamsStringify(context.query);
        }

        const defaultHeaders: HTTPHeaders = {};
        const userAgent = this.configuration.userAgent;
        if (userAgent) {
            defaultHeaders['User-Agent'] = userAgent;
        }
        const headers = Object.assign(defaultHeaders, this.configuration.headers, context.headers);
        Object.keys(headers).forEach(key => headers[key] === undefined ? delete headers[key] : {});

        const initOverrideFn =
            typeof initOverrides === "function"
                ? initOverrides
                : async () => initOverrides;

        const initParams = {
            method: context.method,
            headers,
            body: context.body,
            credentials: this.configuration.credentials,
        };

        const overriddenInit: RequestInit = {
            ...initParams,
            ...(await initOverrideFn({
                init: initParams,
                context,
            }))
        };

        let body: any;
        if (isFormData(overriddenInit.body)
            || (overriddenInit.body instanceof URLSearchParams)
            || isBlob(overriddenInit.body)) {
          body = overriddenInit.body;
        } else if (this.isJsonMime(headers['Content-Type'])) {
          body = JSON.stringify(overriddenInit.body);
        } else {
          body = overriddenInit.body;
        }

        const init: RequestInit = {
            ...overriddenInit,
            body
        };

        return { url, init };
    }

    private fetchApi = async (url: string, init: RequestInit) => {
        let fetchParams = { url, init };
        for (const middleware of this.middleware) {
            if (middleware.pre) {
                fetchParams = await middleware.pre({
                    fetch: this.fetchApi,
                    ...fetchParams,
                }) || fetchParams;
            }
        }
        let response: Response | undefined = undefined;
        try {
            response = await (this.configuration.fetchApi || fetch)(fetchParams.url, fetchParams.init);
        } catch (e) {
            for (const middleware of this.middleware) {
                if (middleware.onError) {
                    response = await middleware.onError({
                        fetch: this.fetchApi,
                        url: fetchParams.url,
                        init: fetchParams.init,
                        error: e,
                        response: response ? response.clone() : undefined,
                    }) || response;
                }
            }
            if (response === undefined) {
              if (e instanceof Error) {
                throw new FetchError(e, 'The request failed and the interceptors did not return an alternative response');
              } else {
                throw e;
              }
            }
        }
        for (const middleware of this.middleware) {
            if (middleware.post) {
                response = await middleware.post({
                    fetch: this.fetchApi,
                    url: fetchParams.url,
                    init: fetchParams.init,
                    response: response.clone(),
                }) || response;
            }
        }
        return response;
    }

    /**
     * Create a shallow clone of `this` by constructing a new instance
     * and then shallow cloning data members.
     */
    private clone<T extends BaseAPI>(this: T): T {
        const constructor = this.constructor as any;
        const next = new constructor(this.configuration);
        next.middleware = this.middleware.slice();
        return next;
    }
};

function isBlob(value: any): value is Blob {
    return typeof Blob !== 'undefined' && value instanceof Blob;
}

function isFormData(value: any): value is FormData {
    return typeof FormData !== "undefined" && value instanceof FormData;
}

function sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
}

interface TimeoutHandle {
    signal?: AbortSignal;
    cancel: () => void;
}

function applyTimeout(timeoutMs: number | undefined, existing?: AbortSignal | null): TimeoutHandle {
    if (!timeoutMs || timeoutMs <= 0) {
        return { signal: existing ?? undefined, cancel: () => {} };
    }
    const controller = new AbortController();
    const timer = setTimeout(
        () => controller.abort(new DOMException(`Request timed out after ${timeoutMs} ms`, 'TimeoutError')),
        timeoutMs,
    );
    const onAbort = () => controller.abort((existing as any)?.reason);
    if (existing) {
        if (existing.aborted) {
            controller.abort((existing as any).reason);
        } else {
            existing.addEventListener('abort', onAbort, { once: true });
        }
    }
    return {
        signal: controller.signal,
        cancel: () => {
            clearTimeout(timer);
            if (existing) {
                existing.removeEventListener('abort', onAbort);
            }
        },
    };
}

const DEFAULT_RETRYABLE_STATUSES = [429, 500, 502, 503, 504];

function isRetryableStatus(status: number, retry?: RetryConfig): boolean {
    const statuses = retry?.retryableStatuses ?? DEFAULT_RETRYABLE_STATUSES;
    return statuses.indexOf(status) !== -1;
}

/**
 * A thrown `fetch` failure (network error: DNS, connection reset, TLS) is
 * retryable, but a deliberate abort - whether caller-initiated or from the
 * `timeoutMs` deadline - is not. Aborts surface as a {@link FetchError} whose
 * `cause` is an `AbortError`/`TimeoutError`.
 */
function isRetryableNetworkError(error: unknown): boolean {
    if (!(error instanceof FetchError)) {
        return false;
    }
    const name = (error.cause as { name?: string } | undefined)?.name;
    return name !== 'AbortError' && name !== 'TimeoutError';
}

/** Exponential backoff with jitter, capped at `maxDelayMs`. */
function backoffDelay(attempt: number, retry?: RetryConfig): number {
    const base = retry?.retryDelayMs ?? 500;
    const cap = retry?.maxDelayMs ?? 30000;
    const backoff = Math.min(base * Math.pow(2, attempt), cap);
    return backoff + Math.random() * backoff * 0.2;
}

function computeRetryDelay(response: Response, attempt: number, retry?: RetryConfig): number {
    const cap = retry?.maxDelayMs ?? 30000;
    if ((retry?.respectRetryAfter ?? true) && response.headers) {
        const retryAfter = response.headers.get('Retry-After');
        if (retryAfter) {
            const secs = Number(retryAfter);
            if (!Number.isNaN(secs)) {
                return Math.min(secs * 1000, cap);
            }
            const when = Date.parse(retryAfter);
            if (!Number.isNaN(when)) {
                return Math.min(Math.max(0, when - Date.now()), cap);
            }
        }
    }
    return backoffDelay(attempt, retry);
}

export class RequiredError extends Error {
    override name: "RequiredError" = "RequiredError";
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

export type FetchAPI = WindowOrWorkerGlobalScope['fetch'];

export type Json = any;
export type HTTPMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | 'HEAD';
export type HTTPHeaders = { [key: string]: string };
export type HTTPQuery = { [key: string]: string | number | null | boolean | Array<string | number | null | boolean> | Set<string | number | null | boolean> | HTTPQuery };
export type HTTPBody = Json | FormData | URLSearchParams;
export type HTTPRequestInit = { headers?: HTTPHeaders; method: HTTPMethod; credentials?: RequestCredentials; body?: HTTPBody };
export type ModelPropertyNaming = 'camelCase' | 'snake_case' | 'PascalCase' | 'original';

export type InitOverrideFunction = (requestContext: { init: HTTPRequestInit, context: RequestOpts }) => Promise<RequestInit>

export interface FetchParams {
    url: string;
    init: RequestInit;
}

export interface RequestOpts {
    path: string;
    method: HTTPMethod;
    headers: HTTPHeaders;
    query?: HTTPQuery;
    body?: HTTPBody;
}

export function querystring(params: HTTPQuery, prefix: string = ''): string {
    return Object.keys(params)
        .map(key => querystringSingleKey(key, params[key], prefix))
        .filter(part => part.length > 0)
        .join('&');
}

function querystringSingleKey(key: string, value: string | number | null | undefined | boolean | Array<string | number | null | boolean> | Set<string | number | null | boolean> | HTTPQuery, keyPrefix: string = ''): string {
    const fullKey = keyPrefix + (keyPrefix.length ? `[${key}]` : key);
    if (value instanceof Array) {
        const multiValue = value.map(singleValue => encodeURIComponent(String(singleValue)))
            .join(`&${encodeURIComponent(fullKey)}=`);
        return `${encodeURIComponent(fullKey)}=${multiValue}`;
    }
    if (value instanceof Set) {
        const valueAsArray = Array.from(value);
        return querystringSingleKey(key, valueAsArray, keyPrefix);
    }
    if (value instanceof Date) {
        return `${encodeURIComponent(fullKey)}=${encodeURIComponent(value.toISOString())}`;
    }
    if (value instanceof Object) {
        return querystring(value as HTTPQuery, fullKey);
    }
    return `${encodeURIComponent(fullKey)}=${encodeURIComponent(String(value))}`;
}

export function exists(json: any, key: string) {
    const value = json[key];
    return value !== null && value !== undefined;
}

export function mapValues(data: any, fn: (item: any) => any) {
    const result: { [key: string]: any } = {};
    for (const key of Object.keys(data)) {
        result[key] = fn(data[key]);
    }
    return result;
}

export function canConsumeForm(consumes: Consume[]): boolean {
    for (const consume of consumes) {
        if ('multipart/form-data' === consume.contentType) {
            return true;
        }
    }
    return false;
}

export interface Consume {
    contentType: string;
}

export interface RequestContext {
    fetch: FetchAPI;
    url: string;
    init: RequestInit;
}

export interface ResponseContext {
    fetch: FetchAPI;
    url: string;
    init: RequestInit;
    response: Response;
}

export interface ErrorContext {
    fetch: FetchAPI;
    url: string;
    init: RequestInit;
    error: unknown;
    response?: Response;
}

export interface Middleware {
    pre?(context: RequestContext): Promise<FetchParams | void>;
    post?(context: ResponseContext): Promise<Response | void>;
    onError?(context: ErrorContext): Promise<Response | void>;
}

export interface ApiResponse<T> {
    raw: Response;
    value(): Promise<T>;
}

export interface ResponseTransformer<T> {
    (json: any): T;
}

export class JSONApiResponse<T> {
    constructor(public raw: Response, private transformer: ResponseTransformer<T> = (jsonValue: any) => jsonValue) {}

    async value(): Promise<T> {
        return this.transformer(await this.raw.json());
    }
}

export class VoidApiResponse {
    constructor(public raw: Response) {}

    async value(): Promise<void> {
        return undefined;
    }
}

export class BlobApiResponse {
    constructor(public raw: Response) {}

    async value(): Promise<Blob> {
        return await this.raw.blob();
    };
}

export class TextApiResponse {
    constructor(public raw: Response) {}

    async value(): Promise<string> {
        return await this.raw.text();
    };
}
